### ISSUE TITLE
import org.jouvieje.libloader

### ISSUE THREAD

**Issue by tokazio** [jerome-jouvie/NativeBass#4]
Please, can you give me 'org.jouvieje.libloader' then i can recompile NativeBass?

**Comment by ramonberrutti** [comment]
You found this LibLoader?

**Comment by jerome-jouvie** [comment]
Hi,

Sorry I was not notified about the issue you've created. Please find the LibLoader library in the repository:

https://github.com/jerome-jouvie/LibLoader

Best regards,

Jérôme Jouvie
